### ISSUE TITLE
skokinarciarskie.pl

### ISSUE THREAD

**Issue by blocker999** [FiltersHeroes/PolishAntiAnnoyingSpecialSupplement#219]
### System operacyjny (Operating system)

Windows

### Przeglądarka internetowa (Web browser)

Comodo Dragon Version 98.0.4758.102

### Bloker (Blocker)

uBlock Origin 1.41.8

### Używane listy filtrów (Used filter lists)

1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda 
3. Polski Antyirytujący Dodatek Specjalny 
4. 
5. 

### Dodatkowe informacje mogące mieć znaczenie (Additional information that may be relevant)

( u góry )

**Comment by krystian3w** [comment]
Ja mam blokowane  tym: https://github.com/FiltersHeroes/PolishAntiAnnoyingSpecialSupplement/blob/a74f36ed2a5cb487e5bc251f68e2feb35cfa6f13/sections/specyficzne_blokujace.txt#L6

uBo nie wspiera generic-block.
