### ISSUE TITLE
grupa - helion.pl

### ISSUE THREAD

**Issue by blocker999** [FiltersHeroes/PolishAntiAnnoyingSpecialSupplement#230]
### System operacyjny (Operating system)

Windows

### Przeglądarka internetowa (Web browser)

Comodo Dragon Version 102.0.5005.61 (64-bitowa)

### Bloker (Blocker)

uBlock Origin 1.43.0

### Używane listy filtrów (Used filter lists)

1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda 
3. Polski Antyirytujący Dodatek Specjalny 
4. 
5. 

### Link bezpośredni (A specific URL)

```markdown
- sensus.pl

- dlabystrzakow.pl

- ebookpoint.pl

- onepress.pl

- bezdroza.pl
```

### Dodatkowe informacje mogące mieć znaczenie (Additional information that may be relevant)

( button )

**Comment by krystian3w** [comment]
Bystrzaki nie prowadzą RSS buttonem.
