### ISSUE TITLE
laptopshop.pl

### ISSUE THREAD

**Issue by blocker999** [FiltersHeroes/PolishAntiAnnoyingSpecialSupplement#256]
RSS (po lewo)

`https://laptopshop.pl/Jak-ozywic-martwa-baterie-do-laptopa-blog-pol-1417178519.html`

**Comment by hawkeye116477** [comment]
https://github.com/FiltersHeroes/PolishAntiAnnoyingSpecialSupplement/commit/22f6512fa1271b3db90851d8207705f3cf6f9a4b
